CREATE SEQUENCE CURSO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSCRIPCION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RESUMEN_MQ_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONTENIDO_CURSO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EXAMEN_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CALIFICACION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INTENTO_EXAMEN_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CURSOS (
    ID NUMBER(19) PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    INSTRUCTOR VARCHAR2(120) NOT NULL,
    DURACION VARCHAR2(80) NOT NULL,
    COSTO NUMBER(12, 2) NOT NULL
);

CREATE TABLE INSCRIPCIONES (
    ID NUMBER(19) PRIMARY KEY,
    ESTUDIANTE_NOMBRE VARCHAR2(120) NOT NULL,
    ESTUDIANTE_EMAIL VARCHAR2(120) NOT NULL,
    TOTAL NUMBER(12, 2) NOT NULL,
    FECHA_INSCRIPCION TIMESTAMP NOT NULL
);

CREATE TABLE INSCRIPCION_CURSOS (
    INSCRIPCION_ID NUMBER(19) NOT NULL,
    CURSO_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_INSCRIPCION_CURSOS PRIMARY KEY (INSCRIPCION_ID, CURSO_ID),
    CONSTRAINT FK_INSCRIPCION_CURSO_INS FOREIGN KEY (INSCRIPCION_ID) REFERENCES INSCRIPCIONES(ID),
    CONSTRAINT FK_INSCRIPCION_CURSO_CUR FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID)
);

CREATE TABLE RESUMENES_INSCRIPCION_MQ (
    ID NUMBER(19) PRIMARY KEY,
    NUMERO_RESUMEN NUMBER(19) NOT NULL,
    ESTUDIANTE_NOMBRE VARCHAR2(120) NOT NULL,
    ESTUDIANTE_EMAIL VARCHAR2(120) NOT NULL,
    FECHA_INSCRIPCION TIMESTAMP NOT NULL,
    TOTAL NUMBER(12, 2) NOT NULL,
    CONTENIDO_RESUMEN CLOB NOT NULL,
    FECHA_PROCESAMIENTO TIMESTAMP NOT NULL
);

CREATE TABLE CONTENIDOS_CURSO (
    ID NUMBER(19) PRIMARY KEY,
    CURSO_ID NUMBER(19) NOT NULL,
    TITULO VARCHAR2(160) NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    URL_CONTENIDO VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_CONTENIDO_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID)
);

CREATE TABLE EXAMENES (
    ID NUMBER(19) PRIMARY KEY,
    CURSO_ID NUMBER(19) NOT NULL,
    TITULO VARCHAR2(160) NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    FECHA_DISPONIBLE TIMESTAMP NOT NULL,
    PUNTAJE_MAXIMO NUMBER(5, 2) NOT NULL,
    CONSTRAINT FK_EXAMEN_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID)
);

CREATE TABLE CALIFICACIONES (
    ID NUMBER(19) PRIMARY KEY,
    INSCRIPCION_ID NUMBER(19) NOT NULL,
    EXAMEN_ID NUMBER(19) NOT NULL,
    PUNTAJE NUMBER(5, 2) NOT NULL,
    COMENTARIO VARCHAR2(500),
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_CALIFICACION_INS FOREIGN KEY (INSCRIPCION_ID) REFERENCES INSCRIPCIONES(ID),
    CONSTRAINT FK_CALIFICACION_EXAMEN FOREIGN KEY (EXAMEN_ID) REFERENCES EXAMENES(ID)
);

CREATE TABLE INTENTOS_EXAMEN (
    ID NUMBER(19) PRIMARY KEY,
    INSCRIPCION_ID NUMBER(19) NOT NULL,
    EXAMEN_ID NUMBER(19) NOT NULL,
    ESTADO VARCHAR2(30) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FINALIZACION TIMESTAMP,
    PUNTAJE_OBTENIDO NUMBER(5, 2),
    RESPUESTAS_JSON CLOB,
    COMENTARIO VARCHAR2(500),
    CONSTRAINT FK_INTENTO_INS FOREIGN KEY (INSCRIPCION_ID) REFERENCES INSCRIPCIONES(ID),
    CONSTRAINT FK_INTENTO_EXAMEN FOREIGN KEY (EXAMEN_ID) REFERENCES EXAMENES(ID)
);
